sudo: false
language: node_js
node_js:
  - 4
  - 5
  - 6
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install: if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
install:
  - npm install

before_script:
  - npm prune
script:
  - npm run cover
  - npm run build