sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install: if [[ `npm -v` != 4* ]]; then npm i -g npm@4; fi
before_script:
  - npm prune
script:
  - npm run cover
  - npm run build